### ISSUE TITLE
Regenerating projects or modules 

### ISSUE THREAD

**Issue by moylop260** [acsone/bobtemplates.odoo#10]
@sbidoul 
Good job thanks!

FYI the following python pure library [cookiecutter](https://github.com/ionelmc/cookiecutter-pylibrary) save a `configuration` file with your command line choices.
This allow you to regenerate the full project meta-files with new changes/updates E.g. `.travis.yml`, `.tox`

For the case of this project, maybe we could use this technical to reuse a `configuration` file to create a new module based on configuration stored as default value.

Question: The final focus of this project... Is create a `scaffold` (just create modules) or a `cookiecutter` (create full project too)?

**Comment by sbidoul** [comment]
I know cookiecutter which is similar. I selected mrbob because I like the way you can package several templates in the same python package (bobtemplates.odoo in this case).

With mrbob, you can also have configuration file with pre-answered questions. See [here](http://mrbob.readthedocs.io/en/latest/userguide.html). 

As I wrote in [the doc](https://pypi.python.org/pypi/bobtemplates.odoo), you can already create a new addon, model, wizard and test class with different commands.

To create a new oca project, a new template would need to be created in https://github.com/acsone/bobtemplates.odoo/tree/master/bobtemplates/odoo (eg `oca-project`) with the README, travis.yml etc. Quite easy to do.

**Comment by moylop260** [comment]
Thanks for clarify
